# Generated by Django 4.2 on 2025-01-16 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_name_alter_user_password_alter_user_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pod',
            name='pod_number',
        ),
    ]
