# Generated by Django 4.2 on 2025-01-16 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_pod_pod_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='pod',
            name='custom_name',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
