# Generated by Django 4.2 on 2025-01-17 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_pod_custom_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='crop',
            name='required_light_duration',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='crop',
            name='life_cycle',
            field=models.PositiveIntegerField(help_text='Life cycle in days'),
        ),
    ]
