# Generated by Django 4.2 on 2025-01-20 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_pod_harvest_date_pod_planting_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='pod',
            name='pod_number',
            field=models.PositiveIntegerField(help_text='pod number of the device', null=True),
        ),
        migrations.AlterField(
            model_name='pod',
            name='custom_name',
            field=models.TextField(help_text='Nutrients needed'),
        ),
    ]
