# Generated by Django 4.2 on 2025-01-20 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_pod_pod_number_alter_pod_custom_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pod',
            name='custom_name',
            field=models.TextField(help_text='Custom name for the crop'),
        ),
        migrations.AlterField(
            model_name='pod',
            name='pod_number',
            field=models.PositiveIntegerField(help_text='Pod number of the device'),
        ),
        migrations.AlterUniqueTogether(
            name='pod',
            unique_together={('device', 'pod_number')},
        ),
    ]
