# Generated by Django 4.2 on 2025-01-20 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_pod_custom_name_alter_pod_pod_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pod',
            name='pod_number',
            field=models.PositiveIntegerField(help_text='Pod number of the device', null=True),
        ),
    ]
