# Generated by Django 4.2 on 2025-01-20 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_pod_pod_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pod',
            name='pod_number',
            field=models.PositiveIntegerField(blank=True, help_text='Pod number of the device', null=True),
        ),
    ]
