# Generated by Django 4.2 on 2025-01-20 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_pod_pod_number'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='pod',
            unique_together=set(),
        ),
    ]
