# Generated by Django 4.2 on 2025-01-23 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_pod_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='device_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
