# Generated by Django 4.2 on 2025-01-23 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_todo'),
    ]

    operations = [
        migrations.AddField(
            model_name='pod',
            name='status',
            field=models.CharField(default='Seedling', max_length=255),
        ),
    ]
