# Generated by Django 4.2 on 2025-01-24 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_alter_device_device_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='crop',
            old_name='humidity',
            new_name='optimal_humidity',
        ),
        migrations.RenameField(
            model_name='crop',
            old_name='nutrient',
            new_name='optimal_tds',
        ),
        migrations.RenameField(
            model_name='crop',
            old_name='temperature',
            new_name='optimal_temperature',
        ),
        migrations.RemoveField(
            model_name='crop',
            name='water',
        ),
        migrations.AddField(
            model_name='crop',
            name='fruiting_days',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='crop',
            name='growth_days',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='crop',
            name='harvesting_days',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='crop',
            name='sampling_days',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='crop',
            name='seedling_days',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
