# Generated by Django 4.2 on 2025-01-25 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_rename_humidity_crop_optimal_humidity_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='crop',
            old_name='seedling_days',
            new_name='seeding_days',
        ),
        migrations.RemoveField(
            model_name='crop',
            name='optimal_humidity',
        ),
        migrations.RemoveField(
            model_name='crop',
            name='optimal_tds',
        ),
        migrations.RemoveField(
            model_name='crop',
            name='optimal_temperature',
        ),
        migrations.AddField(
            model_name='crop',
            name='max_optimal_humidity',
            field=models.FloatField(default=70, help_text='Optimal humidity in %'),
        ),
        migrations.AddField(
            model_name='crop',
            name='max_optimal_tds',
            field=models.TextField(default=1000, help_text='Nutrients needed'),
        ),
        migrations.AddField(
            model_name='crop',
            name='max_optimal_temperature',
            field=models.FloatField(default=25, help_text='Optimal temperature in °C'),
        ),
        migrations.AddField(
            model_name='crop',
            name='min_optimal_humidity',
            field=models.FloatField(default=30, help_text='Optimal humidity in %'),
        ),
        migrations.AddField(
            model_name='crop',
            name='min_optimal_tds',
            field=models.TextField(default=600, help_text='Nutrients needed'),
        ),
        migrations.AddField(
            model_name='crop',
            name='min_optimal_temperature',
            field=models.FloatField(default=15, help_text='Optimal temperature in °C'),
        ),
    ]
