# Generated by Django 4.2 on 2025-01-26 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_rename_seedling_days_crop_seeding_days_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pod',
            name='fruiting_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
