# Generated by Django 4.2 on 2025-01-26 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_pod_fruiting_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pod',
            name='harvest_date',
        ),
        migrations.AddField(
            model_name='pod',
            name='harvest_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pod',
            name='harvest_start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
