# Generated by Django 4.2 on 2025-01-26 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_remove_pod_harvest_date_pod_harvest_end_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='created_by',
        ),
    ]
