# Generated by Django 4.2 on 2025-02-03 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_deviceauditlog_delete_auditlog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deviceauditlog',
            name='action',
        ),
        migrations.RemoveField(
            model_name='deviceauditlog',
            name='user',
        ),
        migrations.AddField(
            model_name='deviceauditlog',
            name='error_codes',
            field=models.TextField(help_text='Custom name for the crop', null=True),
        ),
        migrations.AddField(
            model_name='deviceauditlog',
            name='humidity',
            field=models.FloatField(help_text='current humidity', null=True),
        ),
        migrations.AddField(
            model_name='deviceauditlog',
            name='tds',
            field=models.TextField(help_text='current tds', null=True),
        ),
        migrations.AddField(
            model_name='deviceauditlog',
            name='temperature',
            field=models.FloatField(help_text='current temperature', null=True),
        ),
        migrations.AddField(
            model_name='deviceauditlog',
            name='water_temperature',
            field=models.TextField(help_text='current water temperature', null=True),
        ),
    ]
