# Generated by Django 4.2 on 2025-04-30 15:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0029_blog'),
    ]

    operations = [
        migrations.CreateModel(
            name='ValidDIN',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('din', models.CharField(max_length=50, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PodAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crop_name', models.CharField(max_length=255)),
                ('planting_date', models.DateField()),
                ('log_date', models.DateTimeField(auto_now_add=True)),
                ('action', models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update')], max_length=10)),
                ('crop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pod_audit_logs', to='users.crop')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pod_audit_logs', to='users.device')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pod_audit_logs', to=settings.AUTH_USER_MODEL)),
                ('pod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='users.pod')),
            ],
            options={
                'ordering': ['-log_date'],
            },
        ),
    ]
