name: Deploy to EC2

on:
  push:
    branches:
      - main  # You can specify any branch for deployment.

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python environment
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: SSH to EC2 and deploy
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}  # Your EC2 public IP
          username: ${{ secrets.EC2_USER }}  # e.g., ec2-user
          key: ${{ secrets.EC2_PRIVATE_KEY }}  # Your private SSH key
          port: 22
          script: |
            cd UrbanJungle
            git pull origin main
            source venv/bin/activate
            pip install -r requirements.txt
            
            # Apply database migrations
            python manage.py makemigrations
            python manage.py migrate
            
            # Collect static files (optional)
            python manage.py collectstatic --noinput
            
            # Restart services
            sudo systemctl restart nginx
            sudo systemctl restart gunicorn


