name: Deploy to DigitalOcean

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: SSH to Droplet and deploy
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.DROPLET_HOST }}
          username: ${{ secrets.DROPLET_USER }}
          key: ${{ secrets.DROPLET_KEY }}
          port: 22
          script: |
            # Navigate to project folder (if exists) or clone it
            cd /home/UrbanJungle
            git reset --hard HEAD  # Discard all local changes
            #git clean -fd          # Remove untracked files
            git pull origin main

            # Create Virtual Environment (if not exists)
            # python3 -m venv venv
            source venv/bin/activate

            # Install dependencies
            pip install --upgrade pip
            pip install -r requirements.txt

            # Run Migrations
            # python manage.py makemigrations --noinput
            python manage.py migrate --noinput

            # Collect static files
            python manage.py collectstatic --noinput

            # Restart services
            sudo supervisorctl reread
            sudo supervisorctl update
            sudo supervisorctl start django

            sudo systemctl restart nginx
            sudo systemctl restart gunicorn
            sudo systemctl restart redis
            sudo systemctl restart celery
            sudo systemctl restart celery-beat
